- name: play-01
  hosts: web
  tasks: 
  - name: play-01 task-01
    ansible.builtin.debug:
      msg: "this is from play 1 and task 1"

- name: play-02 
  hosts: web
  tasks:
  - name: play-02 task-01
    ansible.builtin.debug:
      msg: "this is from play-02 ans task-01"

ansible-init
      